/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel;

import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Cursor;
import java.awt.GraphicsEnvironment;
import javax.swing.Box;
import javax.swing.JFrame;

/**
 *
 * @author Александр
 */
public class MainForm extends javax.swing.JFrame {
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }
    public static int aboutFormCount = 0;
    public static int OpenClientFormsCount = 0;
    public static int OpenRoomsFormsCount = 0;
    public static int OpenBookedRoomsFormsCount = 0;
    private static int x;
    private static int y;
    private boolean max_size = true;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        developerAddressLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        settingsMenu = new javax.swing.JMenu();
        operationsMenu = new javax.swing.JMenu();
        ClientMenuItem = new javax.swing.JMenuItem();
        RoomsMenuItem = new javax.swing.JMenuItem();
        separator = new javax.swing.JPopupMenu.Separator();
        BookedRoomsMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();
        desizeMenu = new javax.swing.JMenu();
        extendMenu = new javax.swing.JMenu();
        closeMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setSize(new java.awt.Dimension(0, 0));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        mainPanel.setBackground(new java.awt.Color(255, 255, 204));
        mainPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        developerAddressLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        developerAddressLabel.setForeground(new java.awt.Color(51, 51, 0));
        developerAddressLabel.setText("© github.com/AlKulakov");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(530, Short.MAX_VALUE)
                .addComponent(developerAddressLabel)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addComponent(developerAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(0, 448, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuBar.setBackground(new java.awt.Color(255, 204, 102));
        menuBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuBar.setForeground(new java.awt.Color(51, 51, 0));
        menuBar.setBorderPainted(false);
        menuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBar.setEnabled(false);
        menuBar.setFocusable(false);
        menuBar.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        menuBar.setOpaque(true);
        menuBar.setPreferredSize(new java.awt.Dimension(200, 30));
        menuBar.setRequestFocusEnabled(false);
        menuBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                menuBarMouseDragged(evt);
            }
        });
        menuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuBarMousePressed(evt);
            }
        });

        settingsMenu.setBackground(new java.awt.Color(255, 204, 102));
        settingsMenu.setForeground(new java.awt.Color(51, 51, 0));
        settingsMenu.setText("Настройки");
        settingsMenu.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        settingsMenu.setOpaque(true);
        menuBar.add(settingsMenu);

        operationsMenu.setBackground(new java.awt.Color(255, 204, 102));
        operationsMenu.setForeground(new java.awt.Color(51, 51, 0));
        operationsMenu.setText("Операции");
        operationsMenu.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        operationsMenu.setOpaque(true);
        operationsMenu.setPreferredSize(new java.awt.Dimension(100, 35));

        ClientMenuItem.setBackground(new java.awt.Color(255, 204, 102));
        ClientMenuItem.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        ClientMenuItem.setForeground(new java.awt.Color(51, 51, 0));
        ClientMenuItem.setText(" Открыть данные клиентов");
        ClientMenuItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ClientMenuItem.setContentAreaFilled(false);
        ClientMenuItem.setOpaque(true);
        ClientMenuItem.setPreferredSize(new java.awt.Dimension(350, 35));
        ClientMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientMenuItemActionPerformed(evt);
            }
        });
        operationsMenu.add(ClientMenuItem);

        RoomsMenuItem.setBackground(new java.awt.Color(255, 204, 102));
        RoomsMenuItem.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        RoomsMenuItem.setForeground(new java.awt.Color(51, 51, 0));
        RoomsMenuItem.setText(" Открыть данные номеров");
        RoomsMenuItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RoomsMenuItem.setContentAreaFilled(false);
        RoomsMenuItem.setOpaque(true);
        RoomsMenuItem.setPreferredSize(new java.awt.Dimension(350, 35));
        RoomsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomsMenuItemActionPerformed(evt);
            }
        });
        operationsMenu.add(RoomsMenuItem);

        separator.setBackground(new java.awt.Color(255, 204, 102));
        separator.setForeground(new java.awt.Color(255, 255, 204));
        separator.setOpaque(true);
        operationsMenu.add(separator);

        BookedRoomsMenuItem.setBackground(new java.awt.Color(255, 204, 102));
        BookedRoomsMenuItem.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        BookedRoomsMenuItem.setForeground(new java.awt.Color(51, 51, 0));
        BookedRoomsMenuItem.setText(" Открыть забронированные номера");
        BookedRoomsMenuItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BookedRoomsMenuItem.setContentAreaFilled(false);
        BookedRoomsMenuItem.setOpaque(true);
        BookedRoomsMenuItem.setPreferredSize(new java.awt.Dimension(350, 35));
        BookedRoomsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookedRoomsMenuItemActionPerformed(evt);
            }
        });
        operationsMenu.add(BookedRoomsMenuItem);

        menuBar.add(operationsMenu);

        helpMenu.setBackground(new java.awt.Color(255, 204, 102));
        helpMenu.setForeground(new java.awt.Color(51, 51, 0));
        helpMenu.setText("Справка");
        helpMenu.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        helpMenu.setOpaque(true);

        aboutMenuItem.setBackground(new java.awt.Color(255, 204, 102));
        aboutMenuItem.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        aboutMenuItem.setForeground(new java.awt.Color(51, 51, 0));
        aboutMenuItem.setText("О программе");
        aboutMenuItem.setOpaque(true);
        aboutMenuItem.setPreferredSize(new java.awt.Dimension(169, 30));
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        desizeMenu.setBackground(new java.awt.Color(0, 153, 153));
        desizeMenu.setForeground(new java.awt.Color(51, 51, 0));
        desizeMenu.setText("   _");
        desizeMenu.setFocusable(false);
        desizeMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        desizeMenu.setPreferredSize(new java.awt.Dimension(40, 26));
        desizeMenu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                desizeMenuMenuSelected(evt);
            }
        });
        desizeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                desizeMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                desizeMenuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                desizeMenuMousePressed(evt);
            }
        });

        menuBar.add(Box.createHorizontalGlue());

        menuBar.add(desizeMenu);

        extendMenu.setBackground(new java.awt.Color(0, 153, 153));
        extendMenu.setForeground(new java.awt.Color(51, 51, 0));
        extendMenu.setText("   ▯");
        extendMenu.setFocusable(false);
        extendMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        extendMenu.setPreferredSize(new java.awt.Dimension(40, 26));
        extendMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                extendMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                extendMenuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                extendMenuMousePressed(evt);
            }
        });
        menuBar.add(extendMenu);

        closeMenu.setBackground(new java.awt.Color(255, 204, 102));
        closeMenu.setForeground(new java.awt.Color(51, 51, 0));
        closeMenu.setText("   X");
        closeMenu.setFocusable(false);
        closeMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        closeMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeMenu.setMinimumSize(new java.awt.Dimension(40, 26));
        closeMenu.setOpaque(true);
        closeMenu.setPreferredSize(new java.awt.Dimension(40, 26));
        closeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMenuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMenuMousePressed(evt);
            }
        });

        closeMenu.setForeground(new Color(51, 51, 0));

        menuBar.add(closeMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed

        if(aboutFormCount<1){
            aboutFormCount++;
            AboutFrame aboutFrame = new AboutFrame();
            aboutFrame.setVisible(true);
            aboutFrame.setLocationRelativeTo(null);
            aboutFrame.pack();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void closeMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMenuMousePressed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_closeMenuMousePressed

    private void closeMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMenuMouseEntered
        closeMenu.setSelected(false);
        closeMenu.setBackground(Color.red);
        closeMenu.setForeground(new Color(255, 255, 204));// TODO add your handling code here:
    }//GEN-LAST:event_closeMenuMouseEntered

    private void closeMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMenuMouseExited

        closeMenu.setBackground(null);
        closeMenu.setForeground(new Color(51, 51, 0));        // TODO add your handling code here:
    }//GEN-LAST:event_closeMenuMouseExited

    private void desizeMenuMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_desizeMenuMenuSelected
       // TODO add your handling code here:
    }//GEN-LAST:event_desizeMenuMenuSelected

    private void desizeMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desizeMenuMouseEntered
        desizeMenu.setSelected(false);
        desizeMenu.setForeground(new Color(255, 255, 204));// TODO add your handling code here:
    }//GEN-LAST:event_desizeMenuMouseEntered

    private void desizeMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desizeMenuMouseExited

        desizeMenu.setBackground(null);
        desizeMenu.setForeground(new Color(51, 51, 0));        // TODO add your handling code here:
    }//GEN-LAST:event_desizeMenuMouseExited

    private void desizeMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desizeMenuMousePressed
        this.setState(ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_desizeMenuMousePressed

    private void menuBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBarMousePressed
        x = evt.getX();
        y = evt.getY();        // TODO add your handling code here:
    }//GEN-LAST:event_menuBarMousePressed

    private void menuBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBarMouseDragged
        this.setLocation(evt.getXOnScreen() - x, evt.getYOnScreen() - y);        // TODO add your handling code here:
    }//GEN-LAST:event_menuBarMouseDragged

    private void extendMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extendMenuMousePressed
        extendMenu.setSelected(false);
        GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
        if(max_size==true){
            this.setExtendedState(NORMAL);
            max_size=false;
        }
        else{
        this.setMaximizedBounds(env.getMaximumWindowBounds());
        this.setExtendedState(MAXIMIZED_BOTH);
        max_size=true;
        }
        this.setLocationRelativeTo(null);// TODO add your handling code here:
    }//GEN-LAST:event_extendMenuMousePressed

    private void extendMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extendMenuMouseEntered

        extendMenu.setBackground(Color.BLUE);
        extendMenu.setForeground(new Color(255, 255, 204));
        extendMenu.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_extendMenuMouseEntered

    private void extendMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extendMenuMouseExited
        extendMenu.setBackground(null);
        extendMenu.setForeground(new Color(51, 51 , 0));// TODO add your handling code here:
    }//GEN-LAST:event_extendMenuMouseExited
    boolean RESIZE = false;
    boolean RESIZE_S = false;
    boolean RESIZE_W = false;
    boolean RESIZE_E = false;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        x = evt.getX();
        y = evt.getY();
        if(x <=this.getWidth() && x >= this.getWidth()-5 && max_size == false){
            RESIZE = true;// TODO add your handling code here:
            RESIZE_E = true;// TODO add your handling code here:
            RESIZE_S = false;
            RESIZE_W = false;
        }
        else if(y <=this.getHeight() && y >= this.getHeight()-5 && max_size == false){
            RESIZE = true;
            RESIZE_S = true;
            RESIZE_W = false;
            RESIZE_E = false;
        }
        
        
        else RESIZE = false;
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
                // TODO add your handling code here:
        if(RESIZE)
            if (!max_size){
                    if(RESIZE_E){
                        if(evt.getX()>500)
                            this.setSize(evt.getX(), this.getHeight());
                    }
                    else if(RESIZE_S){
                        if(evt.getY()>300)
                            this.setSize(this.getWidth(), evt.getY());
                    }
    }
    }//GEN-LAST:event_formMouseDragged

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        
    }//GEN-LAST:event_formMouseEntered

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        x = evt.getX();
        y = evt.getY();
        if (!max_size && aboutFormCount==0)
            if(x <=this.getWidth() && x >= this.getWidth()-5){
                mainPanel.setCursor(new Cursor(E_RESIZE_CURSOR));
            }
            else if(y <=this.getHeight() && y >= this.getHeight()-5){
                mainPanel.setCursor(new Cursor(S_RESIZE_CURSOR));
            }
            
            else mainPanel.setCursor(new Cursor(DEFAULT_CURSOR));// TODO add your handling code here:
    }//GEN-LAST:event_formMouseMoved

    private void ClientMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientMenuItemActionPerformed
        if(OpenClientFormsCount==0) {
            OpenClientsForm openClientsForm = new OpenClientsForm();
            openClientsForm.setVisible(true);
            openClientsForm.setLocationRelativeTo(null);
            openClientsForm.pack();
            OpenClientFormsCount++;
        }
    }//GEN-LAST:event_ClientMenuItemActionPerformed

    private void RoomsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomsMenuItemActionPerformed
        if(OpenRoomsFormsCount==0) {
            OpenRoomsForm openRoomsForm = new OpenRoomsForm();
            openRoomsForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            openRoomsForm.setVisible(true);
            openRoomsForm.setLocationRelativeTo(null);
            openRoomsForm.pack();
            OpenRoomsFormsCount++;
        }// TODO add your handling code here:
    }//GEN-LAST:event_RoomsMenuItemActionPerformed

    private void BookedRoomsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookedRoomsMenuItemActionPerformed
        if(OpenBookedRoomsFormsCount==0) {
            OpenBookedRooms openBookedRooms = new OpenBookedRooms();
            openBookedRooms.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            openBookedRooms.setVisible(true);
            openBookedRooms.setLocationRelativeTo(null);
            openBookedRooms.pack();
            OpenBookedRoomsFormsCount++;
        }        // TODO add your handling code here:
    }//GEN-LAST:event_BookedRoomsMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BookedRoomsMenuItem;
    private javax.swing.JMenuItem ClientMenuItem;
    private javax.swing.JMenuItem RoomsMenuItem;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenu closeMenu;
    private javax.swing.JMenu desizeMenu;
    private javax.swing.JLabel developerAddressLabel;
    private javax.swing.JMenu extendMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu operationsMenu;
    private javax.swing.JPopupMenu.Separator separator;
    private javax.swing.JMenu settingsMenu;
    // End of variables declaration//GEN-END:variables
}
