/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.accounting.UI;

import com.mycompany.accounting.MySqlOperations.AccountingSqlQuery;
import com.mycompany.accounting.UI.ProductForm;
import com.mycompany.accounting.UI.RealizationsForm;
import com.mycompany.accounting.UI.SupplierForm;
import com.mycompany.accounting.UI.SupplyForm;
import com.mycompany.accounting.UI.AboutForm;
import java.awt.Color;
import java.awt.Insets;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;


public class MainForm extends javax.swing.JFrame {
    //Переменные счётчики открытых окон, во избежание многократного открытия.
    public static int productFormCount=0;
    public static int equipFormCount=0;
    public static int supplierFormCount=0;
    public static int supplyFormCount=0;
    public static int realizationFormCount=0;
    public static int aboutFormCount=0;
    
    AccountingSqlQuery accountingQuery = new AccountingSqlQuery();
    public MainForm() {
        //Инициализация компонентов, сгенерированных netbeans, заполнение таблицы из класса с БД запросами.
        initComponents();
        accountingQuery.fillAccountingTable(equipTable, "Оборудование");
        accountingQuery.fillAccountingTable(productTable, "Продукт");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        UIManager.put("TabbedPane.borderHightlightColor", java.awt.Color.BLACK);
        UIManager.put("TabbedPane.darkShadow", java.awt.Color.BLACK);
        UIManager.put("TabbedPane.light", java.awt.Color.BLACK);
        UIManager.put("TabbedPane.selectHighlight", java.awt.Color.BLACK);
        UIManager.put("TabbedPane.darkShadow", java.awt.Color.BLACK);
        UIManager.put("TabbedPane.focus", java.awt.Color.BLACK);
        UIManager.getDefaults().put("TabbedPane.contentBorderInsets", new Insets(0,0,0,0));
        UIManager.getDefaults().put("TabbedPane.tabsOverlapBorder", true);
        UIManager.put("TabbedPane.selected", new Color(102, 102, 102));
        tabbedPane = new javax.swing.JTabbedPane();
        equipAccountingPanel = new javax.swing.JPanel();
        equipScrollPane = new javax.swing.JScrollPane();
        equipTable = new javax.swing.JTable();
        refreshEquipButton = new javax.swing.JButton();
        equipTitleLabel = new javax.swing.JLabel();
        searchEquipField = new javax.swing.JTextField();
        productAccountingPanel = new javax.swing.JPanel();
        productScrollPane = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        refreshProductsButton = new javax.swing.JButton();
        productTitleLabel = new javax.swing.JLabel();
        searchProductField = new javax.swing.JTextField();
        closeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        UIManager.put("PopupMenu.border", new LineBorder(Color.BLACK));
        menuBar = new javax.swing.JMenuBar();
        operationsMenu = new javax.swing.JMenu();
        realizationMenuItem = new javax.swing.JMenuItem();
        supplyMenuItem = new javax.swing.JMenuItem();
        openMenu = new javax.swing.JMenu();
        supplierMenuItem = new javax.swing.JMenuItem();
        equipMenuItem = new javax.swing.JMenuItem();
        productsMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Программа материально-технического учёта");
        setUndecorated(true);

        mainPanel.setBackground(new java.awt.Color(0, 0, 0));

        tabbedPane.setBackground(new java.awt.Color(0, 0, 0));
        tabbedPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabbedPane.setForeground(new java.awt.Color(255, 255, 255));
        tabbedPane.setFocusable(false);
        tabbedPane.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tabbedPane.setOpaque(true);
        tabbedPane.setPreferredSize(new java.awt.Dimension(809, 404));

        equipAccountingPanel.setBackground(new java.awt.Color(255, 255, 255));

        equipScrollPane.setPreferredSize(new java.awt.Dimension(452, 600));

        equipTable.setAutoCreateRowSorter(true);
        equipTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Оборудование", "Описание", "Количество"
            }
        ));
        equipTable.setMaximumSize(new java.awt.Dimension(2147483647, 400));
        equipTable.setPreferredSize(new java.awt.Dimension(225, 300));
        equipScrollPane.setViewportView(equipTable);

        refreshEquipButton.setBackground(new java.awt.Color(255, 153, 0));
        refreshEquipButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshEquipButton.setText("Обновить");
        refreshEquipButton.setFocusPainted(false);
        refreshEquipButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                refreshEquipButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refreshEquipButtonMouseExited(evt);
            }
        });
        refreshEquipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshEquipButtonActionPerformed(evt);
            }
        });

        equipTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        equipTitleLabel.setText("Учёт оборудования");

        searchEquipField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchEquipField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchEquipFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout equipAccountingPanelLayout = new javax.swing.GroupLayout(equipAccountingPanel);
        equipAccountingPanel.setLayout(equipAccountingPanelLayout);
        equipAccountingPanelLayout.setHorizontalGroup(
            equipAccountingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equipAccountingPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(equipAccountingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(refreshEquipButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(equipAccountingPanelLayout.createSequentialGroup()
                        .addComponent(equipTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchEquipField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(equipScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(305, Short.MAX_VALUE))
        );
        equipAccountingPanelLayout.setVerticalGroup(
            equipAccountingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equipAccountingPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(equipAccountingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equipTitleLabel)
                    .addComponent(searchEquipField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(equipScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(refreshEquipButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        tabbedPane.addTab("Учёт оборудования", equipAccountingPanel);

        productAccountingPanel.setBackground(new java.awt.Color(255, 255, 255));

        productScrollPane.setPreferredSize(new java.awt.Dimension(452, 600));

        productTable.setAutoCreateRowSorter(true);
        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Продукт", "Описание", "Количество"
            }
        ));
        productTable.setMaximumSize(new java.awt.Dimension(2147483647, 400));
        productTable.setPreferredSize(new java.awt.Dimension(225, 300));
        productScrollPane.setViewportView(productTable);

        refreshProductsButton.setBackground(new java.awt.Color(255, 153, 0));
        refreshProductsButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshProductsButton.setText("Обновить");
        refreshProductsButton.setFocusPainted(false);
        refreshProductsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                refreshProductsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refreshProductsButtonMouseExited(evt);
            }
        });
        refreshProductsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshProductsButtonActionPerformed(evt);
            }
        });

        productTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        productTitleLabel.setText("Учёт продуктов");

        searchProductField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchProductField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchProductFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout productAccountingPanelLayout = new javax.swing.GroupLayout(productAccountingPanel);
        productAccountingPanel.setLayout(productAccountingPanelLayout);
        productAccountingPanelLayout.setHorizontalGroup(
            productAccountingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productAccountingPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(productAccountingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(refreshProductsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(productAccountingPanelLayout.createSequentialGroup()
                        .addComponent(productTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchProductField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(productScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(305, Short.MAX_VALUE))
        );
        productAccountingPanelLayout.setVerticalGroup(
            productAccountingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productAccountingPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(productAccountingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productTitleLabel)
                    .addComponent(searchProductField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(productScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(refreshProductsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        tabbedPane.addTab("Учёт продуктов", productAccountingPanel);

        closeButton.setBackground(new java.awt.Color(255, 153, 0));
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setText("Закрыть");
        closeButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        closeButton.setFocusPainted(false);
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeButtonMouseExited(evt);
            }
        });
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("https://github.com/AlKulakov");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(10, 10, 10))
        );

        menuBar.setBackground(new java.awt.Color(0, 0, 0));
        menuBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuBar.setForeground(new java.awt.Color(255, 255, 255));
        menuBar.setOpaque(true);

        operationsMenu.setBackground(new java.awt.Color(0, 0, 0));
        operationsMenu.setBorder(null);
        operationsMenu.setForeground(new java.awt.Color(255, 255, 255));
        operationsMenu.setText("Операции");

        realizationMenuItem.setBackground(new java.awt.Color(0, 0, 0));
        realizationMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        realizationMenuItem.setText("Реализация");
        realizationMenuItem.setBorder(null);
        realizationMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizationMenuItemActionPerformed(evt);
            }
        });
        operationsMenu.add(realizationMenuItem);

        supplyMenuItem.setBackground(new java.awt.Color(0, 0, 0));
        supplyMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        supplyMenuItem.setText("Поставка");
        supplyMenuItem.setBorder(null);
        supplyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplyMenuItemActionPerformed(evt);
            }
        });
        operationsMenu.add(supplyMenuItem);

        menuBar.add(operationsMenu);

        openMenu.setBackground(new java.awt.Color(0, 0, 0));
        openMenu.setBorder(null);
        openMenu.setForeground(new java.awt.Color(255, 255, 255));
        openMenu.setText("Открыть");

        supplierMenuItem.setBackground(new java.awt.Color(0, 0, 0));
        supplierMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        supplierMenuItem.setText("Меню поставщиков");
        supplierMenuItem.setBorder(null);
        supplierMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierMenuItemActionPerformed(evt);
            }
        });
        openMenu.add(supplierMenuItem);

        equipMenuItem.setBackground(new java.awt.Color(0, 0, 0));
        equipMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        equipMenuItem.setText("Меню оборудования");
        equipMenuItem.setBorder(null);
        equipMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipMenuItemActionPerformed(evt);
            }
        });
        openMenu.add(equipMenuItem);

        productsMenuItem.setBackground(new java.awt.Color(0, 0, 0));
        productsMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        productsMenuItem.setText("Меню продукта");
        productsMenuItem.setBorder(null);
        productsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsMenuItemActionPerformed(evt);
            }
        });
        openMenu.add(productsMenuItem);

        menuBar.add(openMenu);

        helpMenu.setBackground(new java.awt.Color(0, 0, 0));
        helpMenu.setBorder(null);
        helpMenu.setForeground(new java.awt.Color(255, 255, 255));
        helpMenu.setText("Справка");

        aboutMenuItem.setBackground(new java.awt.Color(0, 0, 0));
        aboutMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        aboutMenuItem.setText("О программе");
        aboutMenuItem.setBorder(null);
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshProductsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshProductsButtonMouseEntered
        //Создание обновления цвета при наведении на кнопку для анимации
        refreshProductsButton.setBackground(Color.white);
        refreshProductsButton.setForeground(new Color(255,153,51));        // TODO add your handling code here:
    }//GEN-LAST:event_refreshProductsButtonMouseEntered

    private void refreshProductsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshProductsButtonMouseExited
        //Создание обновления цвета при наведении на кнопку для анимации
        refreshProductsButton.setBackground(new Color(255,153,51));
        refreshProductsButton.setForeground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_refreshProductsButtonMouseExited

    private void refreshEquipButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshEquipButtonMouseEntered
        //Создание обновления цвета при наведении на кнопку для анимации
        refreshEquipButton.setBackground(Color.white);
        refreshEquipButton.setForeground(new Color(255,153,51));
    }//GEN-LAST:event_refreshEquipButtonMouseEntered

    private void refreshEquipButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshEquipButtonMouseExited
        //Создание обновления цвета при наведении на кнопку для анимации
        refreshEquipButton.setBackground(new Color(255,153,51));
        refreshEquipButton.setForeground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_refreshEquipButtonMouseExited

    private void productsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsMenuItemActionPerformed
        //Открытие окна Меню продуктов при нажатии, счётчик открытых окон
        if(productFormCount<1){
            ProductForm productForm = new ProductForm();
            productForm.setLocationRelativeTo(null);
            productForm.pack();
            productForm.show();
            productFormCount++;
        }
    }//GEN-LAST:event_productsMenuItemActionPerformed

    private void equipMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipMenuItemActionPerformed
        //Открытие окна Меню оборудования при нажатии, счётчик открытых окон
        if(equipFormCount<1){
            EquipForm equipForm = new EquipForm();
            equipForm.setLocationRelativeTo(null);
            equipForm.pack();
            equipForm.show();
            equipFormCount++;
        }
    }//GEN-LAST:event_equipMenuItemActionPerformed

    private void supplierMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierMenuItemActionPerformed
        //Открытие окна Меню поставщиков при нажатии, счётчик открытых окон
        if(supplierFormCount<1){
            SupplierForm supplierForm = new SupplierForm();
            supplierForm.setLocationRelativeTo(null);
            supplierForm.pack();
            supplierForm.show();
            supplierFormCount++;
        }        // TODO add your handling code here:
    }//GEN-LAST:event_supplierMenuItemActionPerformed

    private void realizationMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizationMenuItemActionPerformed
        //Открытие окна Меню реализаций при нажатии, счётчик открытых окон
        if(realizationFormCount<1){
            RealizationsForm realizationForm = new RealizationsForm();
            realizationForm.setLocationRelativeTo(null);
            realizationForm.pack();
            realizationForm.show();
            realizationFormCount++;
        }
    }//GEN-LAST:event_realizationMenuItemActionPerformed

    private void supplyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplyMenuItemActionPerformed
        //Открытие окна Меню поставок при нажатии, счётчик открытых окон
        if(supplyFormCount<1){
            SupplyForm supplyForm = new SupplyForm();
            supplyForm.setLocationRelativeTo(null);
            supplyForm.pack();
            supplyForm.show();
            supplyFormCount++;
        }
    }//GEN-LAST:event_supplyMenuItemActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        //Закрытие программы при нажатии на кнопку
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_closeButtonActionPerformed

    private void closeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseEntered
        //Создание обновления цвета при наведении на кнопку для анимации
        closeButton.setBackground(Color.white);
        closeButton.setForeground(new Color(255,153,51));        // TODO add your handling code here:
    }//GEN-LAST:event_closeButtonMouseEntered

    private void closeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseExited
        
        //Создание обновления цвета при наведении на кнопку для анимации
        closeButton.setBackground(new Color(255,153,51));
        closeButton.setForeground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_closeButtonMouseExited

    private void refreshProductsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshProductsButtonActionPerformed
        //Обновление таблицы при нажатии кнопки
        refreshTable(productTable, "Продукт");
    }//GEN-LAST:event_refreshProductsButtonActionPerformed

    private void refreshEquipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshEquipButtonActionPerformed
        //Обновление таблицы при нажатии кнопки
        refreshTable(equipTable, "Оборудование");        // TODO add your handling code here:
    }//GEN-LAST:event_refreshEquipButtonActionPerformed

    private void searchProductFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchProductFieldKeyTyped
        //Поиск строк в бд по введенному тексту по вводу клавиш в поле поиска
        productTable.setModel(new DefaultTableModel(null, new Object[]{"Продукт", "Описание", "Количество"}));
        accountingQuery.fillAccountingSearchTable(productTable, "Продукт", searchProductField.getText());
        
    }//GEN-LAST:event_searchProductFieldKeyTyped

    private void searchEquipFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchEquipFieldKeyTyped
        //Поиск строк в бд по введенному тексту по вводу клавиш в поле поиска
        equipTable.setModel(new DefaultTableModel(null, new Object[]{"Оборудование", "Описание", "Количество"}));
        accountingQuery.fillAccountingSearchTable(equipTable, "Оборудование", searchEquipField.getText());
    }//GEN-LAST:event_searchEquipFieldKeyTyped

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        if(aboutFormCount<1){
            AboutForm aboutForm = new AboutForm();
            aboutForm.setLocationRelativeTo(null);
            aboutForm.pack();
            aboutForm.show();
            aboutFormCount++;
        }
    }//GEN-LAST:event_aboutMenuItemActionPerformed
    private void refreshTable(JTable table, String type){
        //Обновление таблицы при нажатии кнопки
        table.setModel(new DefaultTableModel(null, new Object[]{type,"Описание", "Количество"}));
        accountingQuery.fillAccountingTable(table, type);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel equipAccountingPanel;
    private javax.swing.JMenuItem equipMenuItem;
    private javax.swing.JScrollPane equipScrollPane;
    private javax.swing.JTable equipTable;
    private javax.swing.JLabel equipTitleLabel;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu openMenu;
    private javax.swing.JMenu operationsMenu;
    private javax.swing.JPanel productAccountingPanel;
    private javax.swing.JScrollPane productScrollPane;
    private javax.swing.JTable productTable;
    private javax.swing.JLabel productTitleLabel;
    private javax.swing.JMenuItem productsMenuItem;
    private javax.swing.JMenuItem realizationMenuItem;
    private javax.swing.JButton refreshEquipButton;
    private javax.swing.JButton refreshProductsButton;
    private javax.swing.JTextField searchEquipField;
    private javax.swing.JTextField searchProductField;
    private javax.swing.JMenuItem supplierMenuItem;
    private javax.swing.JMenuItem supplyMenuItem;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
